#CI项目
name: AutoBuild

#CI计划
on:
  #自动编译：当AutoClean运行完成后
  workflow_run:
    workflows: ["AutoClean"]
    types:
      - completed
  #手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [X86_64,Cudy_Tr3000] #
        SOURCE: [https://github.com/fanchmwrt/fanchmwrt]
        BRANCH: [openwrt-24.10.4]

    uses: ./.github/workflows/OpenWrt-CI.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: Openwrt
      #默认地址
      WRT_IP: 192.168.31.1
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      # #插件调整
      # WRT_PACKAGE: ${{inputs.PACKAGE}}
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #默认WIFI名称
      WRT_SSID: Openwrt
      #默认WIFI密码
      WRT_WORD: 12345678